index:
    path: /
    controller: App\Controller\HomeController::index

#Usuario
login:
    path: /login
    controller: App\Controller\UserController::login

registrarse:
    path: /registrarse
    controller: App\Controller\UserController::registrarUsuario

usuario_perfil:
    path: /usuario/{id}
    controller: App\Controller\UserController::perfilUsuario
    
#Proyecto
nuevoProyecto:
    path: /nuevo/proyecto
    controller: App\Controller\ProyectController::altaProyecto

listaProyectos:
    path: /proyectos
    controller: App\Controller\ProyectController::indice

proyecto:
    path: /proyecto/{id}
    controller: App\Controller\ProyectController::proyecto

editarProyecto:
    path: /proyecto/{id}/editar
    controller: App\Controller\ProyectController::editarProyecto


#Ajax (JsonResponse)
valorar_proyecto:
    path: /proyecto/{id}/valorar
    controller: App\Controller\ValoracionesController::valorarProyecto

eliminar_proyecto:
    path: /proyecto/{id}/eliminar
    controller: App\Controller\ProyectController::eliminarProyecto

CommentarPro:
    path: /proyecto/{id}/comentar
    controller: App\Controller\CommentController::Comentar

#Colaboraciones
Colaborar:
    path: /proyecto/{id}/colaborar
    controller: App\Controller\ColaboradoresController::anadirColaboradores