index:
    path: /
    controller: App\Controller\HomeController::index

#Usuario
login:
    path: /login
    controller: App\Controller\UserController::login

registrarse:
    path: /registrarse
    controller: App\Controller\UserController::registrarUsuario

usuario_perfil:
    path: /usuario/{id}
    controller: App\Controller\UserController::perfilUsuario
topDonation:
    path: /usuario/donaciones/top
    controller: App\Controller\UserController::getTopUsers
    
#Proyecto
nuevoProyecto:
    path: /nuevo/proyecto
    controller: App\Controller\ProyectController::altaProyecto

listaProyectos:
    path: /proyectos
    controller: App\Controller\ProyectController::indice

proyecto:
    path: /proyecto/{id}
    controller: App\Controller\ProyectController::proyecto

editarProyecto:
    path: /proyecto/{id}/editar
    controller: App\Controller\ProyectController::editarProyecto


#Ajax (JsonResponse)
valorar_proyecto:
    path: /proyecto/{id}/valorar
    controller: App\Controller\ValoracionesController::valorarProyecto

eliminar_proyecto:
    path: /proyecto/{id}/eliminar
    controller: App\Controller\ProyectController::eliminarProyecto

CommentarPro:
    path: /proyecto/{id}/comentar
    controller: App\Controller\CommentController::Comentar

Quitar_Colaboracion:
    path: /proyecto/{id}/quitar_colaboracion
    controller: App\Controller\ColaboradoresController::eliminarColaboracion

#Colaboraciones
Colaborar:
    path: /proyecto/{id}/colaborar
    controller: App\Controller\ColaboradoresController::anadirColaboradores

#Seguimiento
seguimientos:
    path: /proyecto/{id}/seguimiento
    controller: App\Controller\SeguimientosController::seguimientos

anyadir_seguimiento:
    path: /proyecto/{id}/seguimiento/nuevo
    controller: App\Controller\SeguimientosController::anyadirSeguimiento

eliminar_seguimiento:
    path: /proyecto/{project}/seguimiento/eliminar/{seguimiento}
    controller: App\Controller\SeguimientosController::eliminarSeguimiento

actualizar_seguimiento:
    path: /proyecto/{project}/seguimiento/{seguimiento}/actualizar
    controller: App\Controller\SeguimientosController::actualizarSeguimiento


