index:
  path: /
  controller: App\Controller\HomeController::index

login:
  path: /login
  controller: App\Controller\UserController::login

registrarse:
  path: /registrarse
  controller: App\Controller\UserController::registrarUsuario

nuevoProyecto:
    path: /nuevo/proyecto
    controller: App\Controller\ProyectController::altaProyecto

