index:
    path: /
    controller: App\Controller\HomeController::index

#Usuario
login:
    path: /login
    controller: App\Controller\UserController::login
logout:
    path: /logout
    controller: App\Controller\UserController::logout

registrarse:
    path: /registrarse
    controller: App\Controller\UserController::registrarUsuario

usuario_perfil:
    path: /usuario/{id}
    controller: App\Controller\UserController::perfilUsuario

topDonation:
    path: /usuario/donaciones/top
    controller: App\Controller\UserController::getTopUsers

editar_usuario:
    path: /usuario/{id}/editar
    controller: App\Controller\UserController::editarUsuario
    
#Proyecto
nuevoProyecto:
    path: /nuevo/proyecto
    controller: App\Controller\ProyectController::altaProyecto

listaProyectos:
    path: /proyectos
    controller: App\Controller\ProyectController::indice

proyecto:
    path: /proyecto/{id}
    controller: App\Controller\ProyectController::proyecto

editarProyecto:
    path: /proyecto/{id}/editar
    controller: App\Controller\ProyectController::editarProyecto

filtraProyectos:
    path: /proyectos/{filtro}/{orden}
    controller: App\Controller\ProyectController::getProyectorByFiltro

eliminar_proyecto:
    path: /proyecto/{id}/eliminar
    controller: App\Controller\ProyectController::eliminarProyecto

quitar_destacado:
    path: /proyecto/{id}/quitar_destacado
    controller: App\Controller\ProyectController:quitarDestacado

#Ajax (JsonResponse)
valorar_proyecto:
    path: /proyecto/{id}/valorar
    controller: App\Controller\ValoracionesController::valorarProyecto

desvalorar_proyecto:
    path: /proyecto/{id}/desvalorar
    controller: App\Controller\ValoracionesController::desvalorarProyecto

quitar_valoracion:
    path: /proyecto/{id}/quitar_valoracion
    controller: App\Controller\ValoracionesController::quitarValoracion

quitar_Colaboracion:
    path: /proyecto/{id}/quitar_colaboracion
    controller: App\Controller\ColaboradoresController::eliminarColaboracion

buscar_tags:
    path: /tags/{nombre}
    controller: App\Controller\TagController::getTags

aceptar_colaboracion:
    path: /colaboracion/{proyecto}/{usuario}/aceptar
    controller: App\Controller\ColaboradoresController::aceptarColaboracion

rechazar_colaboracion:
    path: /colaboracion/{proyecto}/{usuario}/rechazar
    controller: App\Controller\ColaboradoresController::rechazarColaboracion

#Colaboraciones
Colaborar:
    path: /proyecto/{id}/colaborar
    controller: App\Controller\ColaboradoresController::colaborar

#Stripe
premium_payment:
    path: /usuario/destacar/
    controller: App\Controller\PagoController::paymentAction

premium_verify:
    path: /premium/verify/{id}
    controller: App\Controller\PagoController::verifyAction
    options:
        expose: true
        
donar_proyecto:
    path: /proyecto/{id}/donar
    controller: App\Controller\PagoController::DonarProyecto

stripe_webhook:
    path: /stripe/wh
    controller: App\Controller\StripeController::webhookAction



seguimientos:
    path: /proyecto/{id}/seguimiento
    controller: App\Controller\SeguimientosController::seguimientos

anyadir_seguimiento:
    path: /proyecto/{id}/seguimiento/nuevo
    controller: App\Controller\SeguimientosController::anyadirSeguimiento

eliminar_seguimiento:
    path: /proyecto/{project}/seguimiento/eliminar/{seguimiento}
    controller: App\Controller\SeguimientosController::eliminarSeguimiento

actualizar_seguimiento:
    path: /proyecto/{project}/seguimiento/{seguimiento}/actualizar
    controller: App\Controller\SeguimientosController::actualizarSeguimiento
addseguimiento:
    path: /proyecto/{id}/nuevo/seguimiento
    controller: App\Controller\SeguimientosController:anadirseguimientoproyecto
    methods: [POST]

#Comentarios
commentar:
    path: /proyecto/{id}/comentar
    controller: App\Controller\CommentController::Comentar

responder:
    path: /comentario/{id}/responder
    controller: App\Controller\CommentController::responder
    
#Politicas

privacidad:
    path: /politica/privacidad
    controller: App\Controller\HomeController::privacidad

